-- ── P-1 · 0037 fixture · scratch PostgreSQL 17 only. GENERATED FILE. ─────
-- Generated by docs/evidence/d1/phase1/p1-0037-build-fixture.py from
-- docs/evidence/d1/phase1/p1-0037-production-reading-20260925.json.
-- Do not hand-edit: regenerate.
--
-- It reconstructs PRODUCTION's ACL state as read on 2026-09-25T09:13:48Z.
-- The function BODIES are stubs -- 0037 changes privileges, never behaviour,
-- so the body is not part of what is under test. Everything that IS under
-- test is exact: the identity signature, SECURITY DEFINER, volatility, the
-- owner, and the ACL string.

DO $$ BEGIN
  IF current_setting('server_version_num')::int < 170000 THEN
    RAISE EXCEPTION 'fixture needs PostgreSQL 17+ (MAINTAIN)'; END IF;
END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN CREATE ROLE anon NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN CREATE ROLE authenticated NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='service_role') THEN CREATE ROLE service_role NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='supabase_auth_admin') THEN CREATE ROLE supabase_auth_admin NOLOGIN; END IF; END $$;

-- ══ FUNCTIONS ════════════════════════════════════════════════════════════

CREATE FUNCTION public.email_exists(text) RETURNS void
  LANGUAGE sql SECURITY DEFINER STABLE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.email_exists(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.email_exists(text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.email_exists(text) FROM PUBLIC;

CREATE FUNCTION public.get_primary_admin_user_id() RETURNS void
  LANGUAGE sql SECURITY DEFINER STABLE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.get_primary_admin_user_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_primary_admin_user_id() TO anon;
GRANT EXECUTE ON FUNCTION public.get_primary_admin_user_id() TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_primary_admin_user_id() FROM PUBLIC;

CREATE FUNCTION public.get_public_role_user_ids(text) RETURNS void
  LANGUAGE sql SECURITY DEFINER STABLE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.get_public_role_user_ids(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_role_user_ids(text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_public_role_user_ids(text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_public_role_user_ids(text) FROM PUBLIC;

CREATE FUNCTION public.search_certificates(text,text,date) RETURNS void
  LANGUAGE sql SECURITY DEFINER STABLE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.search_certificates(text,text,date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.search_certificates(text,text,date) TO service_role;
REVOKE EXECUTE ON FUNCTION public.search_certificates(text,text,date) FROM PUBLIC;

CREATE FUNCTION public.verify_certificate(text) RETURNS void
  LANGUAGE sql SECURITY DEFINER STABLE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.verify_certificate(text) TO anon;
GRANT EXECUTE ON FUNCTION public.verify_certificate(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_certificate(text) TO service_role;

CREATE FUNCTION public.verify_certificate_by_token(text) RETURNS void
  LANGUAGE sql SECURITY DEFINER STABLE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.verify_certificate_by_token(text) TO anon;
GRANT EXECUTE ON FUNCTION public.verify_certificate_by_token(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_certificate_by_token(text) TO service_role;

CREATE FUNCTION public.verify_staff_id(text) RETURNS void
  LANGUAGE sql SECURITY DEFINER STABLE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.verify_staff_id(text) TO anon;
GRANT EXECUTE ON FUNCTION public.verify_staff_id(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_staff_id(text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.verify_staff_id(text) FROM PUBLIC;

CREATE FUNCTION public.apply_decision_to_remaining(uuid,integer,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.apply_decision_to_remaining(uuid,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.apply_decision_to_remaining(uuid,integer,text) TO anon;
GRANT EXECUTE ON FUNCTION public.apply_decision_to_remaining(uuid,integer,text) TO service_role;

CREATE FUNCTION public.get_broadcast_feed(uuid[],integer) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer) FROM PUBLIC;

CREATE FUNCTION public.fix_certificate_readiness_admin(uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.fix_certificate_readiness_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fix_certificate_readiness_admin(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.fix_certificate_readiness_admin(uuid) TO anon;
REVOKE EXECUTE ON FUNCTION public.fix_certificate_readiness_admin(uuid) FROM PUBLIC;

CREATE FUNCTION public.fix_gift_drift_admin(uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.fix_gift_drift_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fix_gift_drift_admin(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.fix_gift_drift_admin(uuid) TO anon;
REVOKE EXECUTE ON FUNCTION public.fix_gift_drift_admin(uuid) FROM PUBLIC;

CREATE FUNCTION public._gen_competition_order_no() RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public._gen_competition_order_no() TO anon;
GRANT EXECUTE ON FUNCTION public._gen_competition_order_no() TO authenticated;
GRANT EXECUTE ON FUNCTION public._gen_competition_order_no() TO service_role;
REVOKE EXECUTE ON FUNCTION public._gen_competition_order_no() FROM PUBLIC;

CREATE FUNCTION public.submit_competition_entry(uuid,text,text,text[],text[],jsonb,boolean,jsonb) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.submit_competition_entry(uuid,text,text,text[],text[],jsonb,boolean,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_competition_entry(uuid,text,text,text[],text[],jsonb,boolean,jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.submit_competition_entry(uuid,text,text,text[],text[],jsonb,boolean,jsonb) TO service_role;
REVOKE EXECUTE ON FUNCTION public.submit_competition_entry(uuid,text,text,text[],text[],jsonb,boolean,jsonb) FROM PUBLIC;

CREATE FUNCTION public.recompute_entry_from_tag_assignments(uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.recompute_entry_from_tag_assignments(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.recompute_entry_from_tag_assignments(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.recompute_entry_from_tag_assignments(uuid) TO service_role;

CREATE FUNCTION public.get_judging_tag_assignment_counts() RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.get_judging_tag_assignment_counts() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_judging_tag_assignment_counts() TO anon;
GRANT EXECUTE ON FUNCTION public.get_judging_tag_assignment_counts() TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_judging_tag_assignment_counts() FROM PUBLIC;

CREATE FUNCTION public.get_judge_collusion_admin(uuid,integer,numeric) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.get_judge_collusion_admin(uuid,integer,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_judge_collusion_admin(uuid,integer,numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.get_judge_collusion_admin(uuid,integer,numeric) TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_judge_collusion_admin(uuid,integer,numeric) FROM PUBLIC;

CREATE FUNCTION public.recompute_entry_public_status(uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.recompute_entry_public_status(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.recompute_entry_public_status(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.recompute_entry_public_status(uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.recompute_entry_public_status(uuid) FROM PUBLIC;

CREATE FUNCTION public.record_test_agent_run(text,text,text,text,text,text,boolean,integer,text,boolean,boolean,boolean,jsonb,integer,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.record_test_agent_run(text,text,text,text,text,text,boolean,integer,text,boolean,boolean,boolean,jsonb,integer,text) TO anon;
GRANT EXECUTE ON FUNCTION public.record_test_agent_run(text,text,text,text,text,text,boolean,integer,text,boolean,boolean,boolean,jsonb,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_test_agent_run(text,text,text,text,text,text,boolean,integer,text,boolean,boolean,boolean,jsonb,integer,text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.record_test_agent_run(text,text,text,text,text,text,boolean,integer,text,boolean,boolean,boolean,jsonb,integer,text) FROM PUBLIC;

CREATE FUNCTION public.set_write_path(text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.set_write_path(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_write_path(text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_write_path(text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.set_write_path(text) FROM PUBLIC;

CREATE FUNCTION public.get_derived_status_drift_admin() RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.get_derived_status_drift_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_derived_status_drift_admin() TO anon;
GRANT EXECUTE ON FUNCTION public.get_derived_status_drift_admin() TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_derived_status_drift_admin() FROM PUBLIC;

CREATE FUNCTION public.judging_write_decision_atomic(uuid,text,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.judging_write_decision_atomic(uuid,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.judging_write_decision_atomic(uuid,text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.judging_write_decision_atomic(uuid,text,text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.judging_write_decision_atomic(uuid,text,text) FROM PUBLIC;

CREATE FUNCTION public.clear_custom_url() RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.clear_custom_url() TO anon;
GRANT EXECUTE ON FUNCTION public.clear_custom_url() TO authenticated;
GRANT EXECUTE ON FUNCTION public.clear_custom_url() TO service_role;

CREATE FUNCTION public.admin_flag_entry_for_review(uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.admin_flag_entry_for_review(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_flag_entry_for_review(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_flag_entry_for_review(uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.admin_flag_entry_for_review(uuid) FROM PUBLIC;

CREATE FUNCTION public.change_custom_url(text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.change_custom_url(text) TO anon;
GRANT EXECUTE ON FUNCTION public.change_custom_url(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.change_custom_url(text) TO service_role;

CREATE FUNCTION public.get_certificate_drift_admin(uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.get_certificate_drift_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_certificate_drift_admin(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_certificate_drift_admin(uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_certificate_drift_admin(uuid) FROM PUBLIC;

CREATE FUNCTION public.request_withdrawal(numeric,jsonb) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.request_withdrawal(numeric,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.request_withdrawal(numeric,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.request_withdrawal(numeric,jsonb) TO anon;
REVOKE EXECUTE ON FUNCTION public.request_withdrawal(numeric,jsonb) FROM PUBLIC;

CREATE FUNCTION public.admin_rewind_stage(uuid,text,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.admin_rewind_stage(uuid,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_rewind_stage(uuid,text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_rewind_stage(uuid,text,text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.admin_rewind_stage(uuid,text,text) FROM PUBLIC;

CREATE FUNCTION public.backfill_judging_notifications(integer,boolean) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.backfill_judging_notifications(integer,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.backfill_judging_notifications(integer,boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.backfill_judging_notifications(integer,boolean) TO service_role;
REVOKE EXECUTE ON FUNCTION public.backfill_judging_notifications(integer,boolean) FROM PUBLIC;

CREATE FUNCTION public.admin_set_photo_rejected(uuid,integer,boolean,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.admin_set_photo_rejected(uuid,integer,boolean,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_photo_rejected(uuid,integer,boolean,text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_set_photo_rejected(uuid,integer,boolean,text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.admin_set_photo_rejected(uuid,integer,boolean,text) FROM PUBLIC;

CREATE FUNCTION public.admin_search_users(text,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.admin_search_users(text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_search_users(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_search_users(text,text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.admin_search_users(text,text) FROM PUBLIC;

CREATE FUNCTION public.fix_referral_drift_admin(uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.fix_referral_drift_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fix_referral_drift_admin(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.fix_referral_drift_admin(uuid) TO anon;
REVOKE EXECUTE ON FUNCTION public.fix_referral_drift_admin(uuid) FROM PUBLIC;

CREATE FUNCTION public.backfill_tag_decision_drift_admin() RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.backfill_tag_decision_drift_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.backfill_tag_decision_drift_admin() TO anon;
GRANT EXECUTE ON FUNCTION public.backfill_tag_decision_drift_admin() TO service_role;
REVOKE EXECUTE ON FUNCTION public.backfill_tag_decision_drift_admin() FROM PUBLIC;

CREATE FUNCTION public.increment_managed_page_view(text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.increment_managed_page_view(text) TO anon;
GRANT EXECUTE ON FUNCTION public.increment_managed_page_view(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.increment_managed_page_view(text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.increment_managed_page_view(text) FROM PUBLIC;

CREATE FUNCTION public.register_push_token(text,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.register_push_token(text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.register_push_token(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.register_push_token(text,text) TO service_role;

CREATE FUNCTION public.unregister_push_token(text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.unregister_push_token(text) TO anon;
GRANT EXECUTE ON FUNCTION public.unregister_push_token(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unregister_push_token(text) TO service_role;

CREATE FUNCTION public.claim_username(text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.claim_username(text) TO anon;
GRANT EXECUTE ON FUNCTION public.claim_username(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.claim_username(text) TO service_role;

CREATE FUNCTION public.log_client_error(text,text,jsonb,text,text,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.log_client_error(text,text,jsonb,text,text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.log_client_error(text,text,jsonb,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_client_error(text,text,jsonb,text,text,text) TO service_role;

CREATE FUNCTION public.log_app_event(text,text,text,text,text,text,text,text,text,text,integer,text,jsonb,text,text,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.log_app_event(text,text,text,text,text,text,text,text,text,text,integer,text,jsonb,text,text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.log_app_event(text,text,text,text,text,text,text,text,text,text,integer,text,jsonb,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_app_event(text,text,text,text,text,text,text,text,text,text,integer,text,jsonb,text,text,text) TO service_role;

CREATE FUNCTION public.get_broadcast_feed(uuid[],integer,integer,text[]) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer,integer,text[]) TO anon;
GRANT EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer,integer,text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer,integer,text[]) TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer,integer,text[]) FROM PUBLIC;

CREATE FUNCTION public.get_broadcast_feed(uuid[],integer,integer) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer,integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_broadcast_feed(uuid[],integer,integer) FROM PUBLIC;

CREATE FUNCTION public.admin_delete_auth_user(uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.admin_delete_auth_user(uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.admin_delete_auth_user(uuid) FROM PUBLIC;

CREATE FUNCTION public.admin_list_certificates(text,text,integer,integer) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.admin_list_certificates(text,text,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_certificates(text,text,integer,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.admin_list_certificates(text,text,integer,integer) FROM PUBLIC;

CREATE FUNCTION public.admin_purge_orphan_user_data(uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.admin_purge_orphan_user_data(uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.admin_purge_orphan_user_data(uuid) FROM PUBLIC;

CREATE FUNCTION public.admin_reject_wallet_transaction(uuid,uuid,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.admin_reject_wallet_transaction(uuid,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_reject_wallet_transaction(uuid,uuid,text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.admin_reject_wallet_transaction(uuid,uuid,text) FROM PUBLIC;

CREATE FUNCTION public.admin_search_certificate_recipients(text,integer) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.admin_search_certificate_recipients(text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_search_certificate_recipients(text,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.admin_search_certificate_recipients(text,integer) FROM PUBLIC;

CREATE FUNCTION public.admin_search_users_v2(text,text,text,text,integer,integer) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.admin_search_users_v2(text,text,text,text,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_search_users_v2(text,text,text,text,integer,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.admin_search_users_v2(text,text,text,text,integer,integer) FROM PUBLIC;

CREATE FUNCTION public.admin_wallet_credit(uuid,uuid,numeric,text,text,uuid,text,jsonb) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.admin_wallet_credit(uuid,uuid,numeric,text,text,uuid,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_wallet_credit(uuid,uuid,numeric,text,text,uuid,text,jsonb) TO service_role;
REVOKE EXECUTE ON FUNCTION public.admin_wallet_credit(uuid,uuid,numeric,text,text,uuid,text,jsonb) FROM PUBLIC;

CREATE FUNCTION public.approve_deposit(uuid,uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.approve_deposit(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_deposit(uuid,uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.approve_deposit(uuid,uuid) FROM PUBLIC;

CREATE FUNCTION public.create_pending_deposit(uuid,numeric,text,text,jsonb,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.create_pending_deposit(uuid,numeric,text,text,jsonb,text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.create_pending_deposit(uuid,numeric,text,text,jsonb,text) FROM PUBLIC;

CREATE FUNCTION public.emit_notification(text,uuid,integer,uuid,text,text,text,uuid,text,jsonb,text) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.emit_notification(text,uuid,integer,uuid,text,text,text,uuid,text,jsonb,text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.emit_notification(text,uuid,integer,uuid,text,text,text,uuid,text,jsonb,text) FROM PUBLIC;

CREATE FUNCTION public.expire_gift_credit(uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.expire_gift_credit(uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.expire_gift_credit(uuid) FROM PUBLIC;

CREATE FUNCTION public.generate_custom_url(text,uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.generate_custom_url(text,uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.generate_custom_url(text,uuid) FROM PUBLIC;

CREATE FUNCTION public.move_to_dlq(text,text,bigint,jsonb) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.move_to_dlq(text,text,bigint,jsonb) TO service_role;
REVOKE EXECUTE ON FUNCTION public.move_to_dlq(text,text,bigint,jsonb) FROM PUBLIC;

CREATE FUNCTION public.password_verification_hook(jsonb) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.password_verification_hook(jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.password_verification_hook(jsonb) TO supabase_auth_admin;
REVOKE EXECUTE ON FUNCTION public.password_verification_hook(jsonb) FROM PUBLIC;

CREATE FUNCTION public.soft_void_wallet_transactions(uuid[],text,uuid) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.soft_void_wallet_transactions(uuid[],text,uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.soft_void_wallet_transactions(uuid[],text,uuid) FROM PUBLIC;

CREATE FUNCTION public.wallet_ledger_apply_v2(text,uuid,numeric,text,text,text,text,boolean) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.wallet_ledger_apply_v2(text,uuid,numeric,text,text,text,text,boolean) TO service_role;
REVOKE EXECUTE ON FUNCTION public.wallet_ledger_apply_v2(text,uuid,numeric,text,text,text,text,boolean) FROM PUBLIC;

CREATE FUNCTION public.wallet_transaction(uuid,text,numeric,text,uuid,text,jsonb) RETURNS void
  LANGUAGE sql SECURITY DEFINER VOLATILE AS $stub$ SELECT $stub$;
GRANT EXECUTE ON FUNCTION public.wallet_transaction(uuid,text,numeric,text,uuid,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wallet_transaction(uuid,text,numeric,text,uuid,text,jsonb) TO service_role;
REVOKE EXECUTE ON FUNCTION public.wallet_transaction(uuid,text,numeric,text,uuid,text,jsonb) FROM PUBLIC;

-- ══ RELATIONS ════════════════════════════════════════════════════════════
-- The base table every view is built on. Its own ACL is not part of the
-- reading and is not asserted; only the thirteen listed relations are.
CREATE TABLE public._p1_0037_base (id uuid PRIMARY KEY, n integer);

CREATE TABLE public.categories_migration_dropped (id uuid PRIMARY KEY, n integer);
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.categories_migration_dropped TO service_role;

CREATE TABLE public.posts_dead_host_backup_20260812 (id uuid PRIMARY KEY, n integer);
GRANT INSERT, SELECT, UPDATE, DELETE, MAINTAIN ON TABLE public.posts_dead_host_backup_20260812 TO anon;
GRANT INSERT, SELECT, UPDATE, DELETE, MAINTAIN ON TABLE public.posts_dead_host_backup_20260812 TO authenticated;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.posts_dead_host_backup_20260812 TO service_role;

CREATE VIEW public.entry_final_votes AS SELECT id, n FROM public._p1_0037_base;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_final_votes TO anon;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_final_votes TO authenticated;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_final_votes TO service_role;

CREATE VIEW public.entry_final_votes_legacy AS SELECT id, n FROM public._p1_0037_base;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_final_votes_legacy TO anon;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_final_votes_legacy TO authenticated;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_final_votes_legacy TO service_role;

CREATE VIEW public.entry_public_status AS SELECT id, n FROM public._p1_0037_base;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_public_status TO anon;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_public_status TO authenticated;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_public_status TO service_role;

CREATE MATERIALIZED VIEW public.entry_vote_counts AS SELECT id, n FROM public._p1_0037_base;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_vote_counts TO anon;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_vote_counts TO authenticated;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.entry_vote_counts TO service_role;

CREATE VIEW public.judge_comments_owner_safe AS SELECT id, n FROM public._p1_0037_base;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_comments_owner_safe TO authenticated;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_comments_owner_safe TO anon;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_comments_owner_safe TO service_role;

CREATE VIEW public.judge_decisions_owner_safe AS SELECT id, n FROM public._p1_0037_base;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_decisions_owner_safe TO authenticated;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_decisions_owner_safe TO anon;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_decisions_owner_safe TO service_role;

CREATE VIEW public.judge_tag_assignments_owner_safe AS SELECT id, n FROM public._p1_0037_base;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_tag_assignments_owner_safe TO authenticated;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_tag_assignments_owner_safe TO anon;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_tag_assignments_owner_safe TO service_role;

CREATE VIEW public.judge_tag_assignments_public_r4 AS SELECT id, n FROM public._p1_0037_base;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_tag_assignments_public_r4 TO anon;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_tag_assignments_public_r4 TO authenticated;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judge_tag_assignments_public_r4 TO service_role;

CREATE VIEW public.judging_progression_audit AS SELECT id, n FROM public._p1_0037_base;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.judging_progression_audit TO service_role;

CREATE VIEW public.profiles_public AS SELECT id, n FROM public._p1_0037_base;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.profiles_public TO anon;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.profiles_public TO authenticated;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.profiles_public TO service_role;

CREATE VIEW public.v_judging_drift AS SELECT id, n FROM public._p1_0037_base;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.v_judging_drift TO anon;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.v_judging_drift TO authenticated;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.v_judging_drift TO service_role;

-- ══ DEFAULT ACL (owner postgres, schema public) ══════════════════════════
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO service_role;

-- ══ THE FIXTURE ASSERTS ITSELF AGAINST THE READING ═══════════════════════
-- Byte-for-byte, every string. A fixture that is approximately production is
-- not evidence about production.
DO $verify$
DECLARE got text; diffs int := 0; n int := 0;
BEGIN
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.email_exists(text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'email_exists(text)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.get_primary_admin_user_id()');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'get_primary_admin_user_id()', '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.get_public_role_user_ids(text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'get_public_role_user_ids(text)', '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.search_certificates(text,text,date)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'search_certificates(text,text,date)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.verify_certificate(text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'verify_certificate(text)', '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.verify_certificate_by_token(text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'verify_certificate_by_token(text)', '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.verify_staff_id(text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'verify_staff_id(text)', '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.apply_decision_to_remaining(uuid,integer,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{=X/postgres,postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'apply_decision_to_remaining(uuid,integer,text)', '{=X/postgres,postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.get_broadcast_feed(uuid[],integer)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'get_broadcast_feed(uuid[],integer)', '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.fix_certificate_readiness_admin(uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres,anon=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'fix_certificate_readiness_admin(uuid)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres,anon=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.fix_gift_drift_admin(uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres,anon=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'fix_gift_drift_admin(uuid)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres,anon=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public._gen_competition_order_no()');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', '_gen_competition_order_no()', '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.submit_competition_entry(uuid,text,text,text[],text[],jsonb,boolean,jsonb)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'submit_competition_entry(uuid,text,text,text[],text[],jsonb,boolean,jsonb)', '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.recompute_entry_from_tag_assignments(uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'recompute_entry_from_tag_assignments(uuid)', '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.get_judging_tag_assignment_counts()');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'get_judging_tag_assignment_counts()', '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.get_judge_collusion_admin(uuid,integer,numeric)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'get_judge_collusion_admin(uuid,integer,numeric)', '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.recompute_entry_public_status(uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'recompute_entry_public_status(uuid)', '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.record_test_agent_run(text,text,text,text,text,text,boolean,integer,text,boolean,boolean,boolean,jsonb,integer,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'record_test_agent_run(text,text,text,text,text,text,boolean,integer,text,boolean,boolean,boolean,jsonb,integer,text)', '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.set_write_path(text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres,anon=X/postgres,authenticated=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'set_write_path(text)', '{postgres=X/postgres,service_role=X/postgres,anon=X/postgres,authenticated=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.get_derived_status_drift_admin()');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'get_derived_status_drift_admin()', '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.judging_write_decision_atomic(uuid,text,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres,anon=X/postgres,authenticated=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'judging_write_decision_atomic(uuid,text,text)', '{postgres=X/postgres,service_role=X/postgres,anon=X/postgres,authenticated=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.clear_custom_url()');
  n := n + 1;
  IF got IS DISTINCT FROM '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'clear_custom_url()', '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.admin_flag_entry_for_review(uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'admin_flag_entry_for_review(uuid)', '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.change_custom_url(text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'change_custom_url(text)', '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.get_certificate_drift_admin(uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'get_certificate_drift_admin(uuid)', '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.request_withdrawal(numeric,jsonb)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres,anon=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'request_withdrawal(numeric,jsonb)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres,anon=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.admin_rewind_stage(uuid,text,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'admin_rewind_stage(uuid,text,text)', '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.backfill_judging_notifications(integer,boolean)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'backfill_judging_notifications(integer,boolean)', '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.admin_set_photo_rejected(uuid,integer,boolean,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'admin_set_photo_rejected(uuid,integer,boolean,text)', '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.admin_search_users(text,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'admin_search_users(text,text)', '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.fix_referral_drift_admin(uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres,anon=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'fix_referral_drift_admin(uuid)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres,anon=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.backfill_tag_decision_drift_admin()');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'backfill_tag_decision_drift_admin()', '{postgres=X/postgres,authenticated=X/postgres,anon=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.increment_managed_page_view(text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'increment_managed_page_view(text)', '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.register_push_token(text,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'register_push_token(text,text)', '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.unregister_push_token(text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'unregister_push_token(text)', '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.claim_username(text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'claim_username(text)', '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.log_client_error(text,text,jsonb,text,text,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'log_client_error(text,text,jsonb,text,text,text)', '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.log_app_event(text,text,text,text,text,text,text,text,text,text,integer,text,jsonb,text,text,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'log_app_event(text,text,text,text,text,text,text,text,text,text,integer,text,jsonb,text,text,text)', '{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.get_broadcast_feed(uuid[],integer,integer,text[])');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'get_broadcast_feed(uuid[],integer,integer,text[])', '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.get_broadcast_feed(uuid[],integer,integer)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'get_broadcast_feed(uuid[],integer,integer)', '{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.admin_delete_auth_user(uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'admin_delete_auth_user(uuid)', '{postgres=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.admin_list_certificates(text,text,integer,integer)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'admin_list_certificates(text,text,integer,integer)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.admin_purge_orphan_user_data(uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'admin_purge_orphan_user_data(uuid)', '{postgres=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.admin_reject_wallet_transaction(uuid,uuid,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'admin_reject_wallet_transaction(uuid,uuid,text)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.admin_search_certificate_recipients(text,integer)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'admin_search_certificate_recipients(text,integer)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.admin_search_users_v2(text,text,text,text,integer,integer)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'admin_search_users_v2(text,text,text,text,integer,integer)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.admin_wallet_credit(uuid,uuid,numeric,text,text,uuid,text,jsonb)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'admin_wallet_credit(uuid,uuid,numeric,text,text,uuid,text,jsonb)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.approve_deposit(uuid,uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'approve_deposit(uuid,uuid)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.create_pending_deposit(uuid,numeric,text,text,jsonb,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'create_pending_deposit(uuid,numeric,text,text,jsonb,text)', '{postgres=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.emit_notification(text,uuid,integer,uuid,text,text,text,uuid,text,jsonb,text)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'emit_notification(text,uuid,integer,uuid,text,text,text,uuid,text,jsonb,text)', '{postgres=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.expire_gift_credit(uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'expire_gift_credit(uuid)', '{postgres=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.generate_custom_url(text,uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'generate_custom_url(text,uuid)', '{postgres=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.move_to_dlq(text,text,bigint,jsonb)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'move_to_dlq(text,text,bigint,jsonb)', '{postgres=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.password_verification_hook(jsonb)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres,supabase_auth_admin=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'password_verification_hook(jsonb)', '{postgres=X/postgres,service_role=X/postgres,supabase_auth_admin=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.soft_void_wallet_transactions(uuid[],text,uuid)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'soft_void_wallet_transactions(uuid[],text,uuid)', '{postgres=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.wallet_ledger_apply_v2(text,uuid,numeric,text,text,text,text,boolean)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'wallet_ledger_apply_v2(text,uuid,numeric,text,text,text,text,boolean)', '{postgres=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.wallet_transaction(uuid,text,numeric,text,uuid,text,jsonb)');
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'wallet_transaction(uuid,text,numeric,text,uuid,text,jsonb)', '{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.categories_migration_dropped'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'categories_migration_dropped', '{postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.posts_dead_host_backup_20260812'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,anon=arwdm/postgres,authenticated=arwdm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'posts_dead_host_backup_20260812', '{postgres=arwdDxtm/postgres,anon=arwdm/postgres,authenticated=arwdm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.entry_final_votes'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'entry_final_votes', '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.entry_final_votes_legacy'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'entry_final_votes_legacy', '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.entry_public_status'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'entry_public_status', '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.entry_vote_counts'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'entry_vote_counts', '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.judge_comments_owner_safe'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,anon=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'judge_comments_owner_safe', '{postgres=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,anon=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.judge_decisions_owner_safe'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,anon=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'judge_decisions_owner_safe', '{postgres=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,anon=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.judge_tag_assignments_owner_safe'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,anon=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'judge_tag_assignments_owner_safe', '{postgres=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,anon=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.judge_tag_assignments_public_r4'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'judge_tag_assignments_public_r4', '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.judging_progression_audit'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'judging_progression_audit', '{postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.profiles_public'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'profiles_public', '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.v_judging_drift'::regclass;
  n := n + 1;
  IF got IS DISTINCT FROM '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'ACL DIFF % : expected % got %', 'v_judging_drift', '{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT defaclacl::text INTO got FROM pg_default_acl
   WHERE defaclrole='postgres'::regrole AND defaclnamespace='public'::regnamespace AND defaclobjtype='r';
  n := n + 1;
  IF got IS DISTINCT FROM '{anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'DEFACL DIFF % : expected % got %', 'r', '{anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}', coalesce(got,'(null)'); END IF;
  SELECT defaclacl::text INTO got FROM pg_default_acl
   WHERE defaclrole='postgres'::regrole AND defaclnamespace='public'::regnamespace AND defaclobjtype='S';
  n := n + 1;
  IF got IS DISTINCT FROM '{anon=rwU/postgres,authenticated=rwU/postgres,service_role=rwU/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'DEFACL DIFF % : expected % got %', 'S', '{anon=rwU/postgres,authenticated=rwU/postgres,service_role=rwU/postgres}', coalesce(got,'(null)'); END IF;
  SELECT defaclacl::text INTO got FROM pg_default_acl
   WHERE defaclrole='postgres'::regrole AND defaclnamespace='public'::regnamespace AND defaclobjtype='f';
  n := n + 1;
  IF got IS DISTINCT FROM '{anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}' THEN diffs := diffs + 1;
    RAISE WARNING 'DEFACL DIFF % : expected % got %', 'f', '{anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}', coalesce(got,'(null)'); END IF;
  IF diffs > 0 THEN
    RAISE EXCEPTION 'FIXTURE IS NOT PRODUCTION-EXACT: % of % ACL strings differ', diffs, n;
  END IF;
  RAISE NOTICE 'FIXTURE BUILT — % ACL strings, all byte-exact against the production reading', n;
END
$verify$;

-- The headline number R-50 reports for production. If the fixture does not
-- reproduce it, nothing measured on the fixture is about production.
DO $count$
DECLARE c int;
BEGIN
  SELECT count(*) INTO c FROM pg_proc p
   WHERE p.pronamespace = 'public'::regnamespace AND p.prokind='f'
     AND p.provolatile='v' AND p.prosecdef AND p.prorettype <> 'trigger'::regtype
     AND has_function_privilege('anon', p.oid, 'EXECUTE');
  IF c <> 33 THEN RAISE EXCEPTION 'expected 33 anon-executable definer volatile functions, got %', c; END IF;
  RAISE NOTICE '33 anon-executable SECURITY DEFINER VOLATILE functions — matches production';
END
$count$;
