#!/usr/bin/env python3
"""D1 · U3 · 20260910_0037 — build the production-exact C-34 fixture.

Emits SQL that reconstructs, on a scratch PostgreSQL 17 cluster, the ACL state
the Owner read on production at 2026-09-25T09:13:48Z: 57 functions, 13
relations and the postgres/public default ACL, every string BYTE-EXACT.

Byte-exact is achievable, and worth the trouble, because aclitem ORDER is not
cosmetic here -- it records the order the grants were made, and a fixture whose
strings merely contain the right grantees would let an ordering bug in a
generated REVOKE list pass unnoticed. The emitted SQL therefore asserts each
string against the reading and RAISEs on the first mismatch, so the fixture
cannot quietly be approximately right.

How the order is reproduced:
  * a function's proacl starts NULL. The first GRANT materialises
    acldefault('f','postgres') = {=X/postgres, postgres=X/postgres} -- PUBLIC
    FIRST -- and appends. So for a reading that starts `=X/postgres`, granting
    the remaining roles in order is enough.
  * for a reading with no PUBLIC entry, the same happens and a single
    `REVOKE EXECUTE ... FROM PUBLIC` at the END removes the `=X` item in place,
    leaving the rest in order.
  * a relation's acldefault has no PUBLIC item, so grants in order suffice.

    python3 docs/evidence/d1/phase1/p1-0037-build-fixture.py > p1-0037-fixture.sql
"""
import json, os, sys
sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
R = json.load(open(os.path.join(HERE, 'p1-0037-production-reading-20260925.json'), encoding='utf-8'))

PRIV = {'a':'INSERT','r':'SELECT','w':'UPDATE','d':'DELETE','D':'TRUNCATE',
        'x':'REFERENCES','t':'TRIGGER','m':'MAINTAIN','X':'EXECUTE','U':'USAGE'}

def items(acl):
    return [i for i in acl.strip('{}').split(',') if i]

def parse(item):
    who, rest = item.split('=', 1)
    privs = rest.split('/')[0]
    return (who or 'PUBLIC'), [PRIV[c] for c in privs]

def q(s):  # SQL string literal
    return "'" + s.replace("'", "''") + "'"

out = []
w = out.append
w("-- ── P-1 · 0037 fixture · scratch PostgreSQL 17 only. GENERATED FILE. ─────")
w("-- Generated by docs/evidence/d1/phase1/p1-0037-build-fixture.py from")
w("-- docs/evidence/d1/phase1/p1-0037-production-reading-20260925.json.")
w("-- Do not hand-edit: regenerate.")
w("--")
w("-- It reconstructs PRODUCTION's ACL state as read on 2026-09-25T09:13:48Z.")
w("-- The function BODIES are stubs -- 0037 changes privileges, never behaviour,")
w("-- so the body is not part of what is under test. Everything that IS under")
w("-- test is exact: the identity signature, SECURITY DEFINER, volatility, the")
w("-- owner, and the ACL string.")
w("")
w("DO $$ BEGIN")
w("  IF current_setting('server_version_num')::int < 170000 THEN")
w("    RAISE EXCEPTION 'fixture needs PostgreSQL 17+ (MAINTAIN)'; END IF;")
w("END $$;")
w("")
for r in ('anon', 'authenticated', 'service_role', 'supabase_auth_admin'):
    w(f"DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='{r}') "
      f"THEN CREATE ROLE {r} NOLOGIN; END IF; END $$;")
w("")
w("-- ══ FUNCTIONS ════════════════════════════════════════════════════════════")

VOLWORD = {'v': 'VOLATILE', 's': 'STABLE', 'i': 'IMMUTABLE'}
for sig, vol, acl in R['functions']:
    name, args = sig[:sig.index('(')], sig[sig.index('(') + 1:-1]
    w("")
    w(f"CREATE FUNCTION public.{name}({args}) RETURNS void")
    w(f"  LANGUAGE sql SECURITY DEFINER {VOLWORD[vol]} AS $stub$ SELECT $stub$;")
    has_public = any(i.startswith('=') for i in items(acl))
    for it in items(acl):
        who, privs = parse(it)
        if who in ('PUBLIC', 'postgres'):
            continue
        w(f"GRANT {', '.join(privs)} ON FUNCTION public.{name}({args}) TO {who};")
    if not has_public:
        w(f"REVOKE EXECUTE ON FUNCTION public.{name}({args}) FROM PUBLIC;")

w("")
w("-- ══ RELATIONS ════════════════════════════════════════════════════════════")
w("-- The base table every view is built on. Its own ACL is not part of the")
w("-- reading and is not asserted; only the thirteen listed relations are.")
w("CREATE TABLE public._p1_0037_base (id uuid PRIMARY KEY, n integer);")
for rel, kind, acl in R['tables']:
    w("")
    if kind == 'r':
        w(f"CREATE TABLE public.{rel} (id uuid PRIMARY KEY, n integer);")
    elif kind == 'v':
        w(f"CREATE VIEW public.{rel} AS SELECT id, n FROM public._p1_0037_base;")
    elif kind == 'm':
        w(f"CREATE MATERIALIZED VIEW public.{rel} AS SELECT id, n FROM public._p1_0037_base;")
    for it in items(acl):
        who, privs = parse(it)
        if who in ('PUBLIC', 'postgres'):
            continue
        w(f"GRANT {', '.join(privs)} ON TABLE public.{rel} TO {who};")
    if any(i.startswith('=') for i in items(acl)):
        w(f"GRANT SELECT ON TABLE public.{rel} TO PUBLIC;")

w("")
w("-- ══ DEFAULT ACL (owner postgres, schema public) ══════════════════════════")
d = R['default_acl_postgres_public']
OBJ = {'r': 'TABLES', 'S': 'SEQUENCES', 'f': 'FUNCTIONS'}
for k, acl in d.items():
    for it in items(acl):
        who, privs = parse(it)
        w(f"ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public "
          f"GRANT {', '.join(privs)} ON {OBJ[k]} TO {who};")

w("")
w("-- ══ THE FIXTURE ASSERTS ITSELF AGAINST THE READING ═══════════════════════")
w("-- Byte-for-byte, every string. A fixture that is approximately production is")
w("-- not evidence about production.")
w("DO $verify$")
w("DECLARE got text; diffs int := 0; n int := 0;")
w("BEGIN")
for sig, vol, acl in R['functions']:
    w(f"  SELECT proacl::text INTO got FROM pg_proc WHERE oid = to_regprocedure('public.{sig}');")
    w(f"  n := n + 1;")
    w(f"  IF got IS DISTINCT FROM {q(acl)} THEN diffs := diffs + 1;")
    w(f"    RAISE WARNING 'ACL DIFF % : expected % got %', {q(sig)}, {q(acl)}, coalesce(got,'(null)'); END IF;")
for rel, kind, acl in R['tables']:
    w(f"  SELECT relacl::text INTO got FROM pg_class WHERE oid = 'public.{rel}'::regclass;")
    w(f"  n := n + 1;")
    w(f"  IF got IS DISTINCT FROM {q(acl)} THEN diffs := diffs + 1;")
    w(f"    RAISE WARNING 'ACL DIFF % : expected % got %', {q(rel)}, {q(acl)}, coalesce(got,'(null)'); END IF;")
for k, acl in d.items():
    w(f"  SELECT defaclacl::text INTO got FROM pg_default_acl")
    w(f"   WHERE defaclrole='postgres'::regrole AND defaclnamespace='public'::regnamespace AND defaclobjtype='{k}';")
    w(f"  n := n + 1;")
    w(f"  IF got IS DISTINCT FROM {q(acl)} THEN diffs := diffs + 1;")
    w(f"    RAISE WARNING 'DEFACL DIFF % : expected % got %', '{k}', {q(acl)}, coalesce(got,'(null)'); END IF;")
w("  IF diffs > 0 THEN")
w("    RAISE EXCEPTION 'FIXTURE IS NOT PRODUCTION-EXACT: % of % ACL strings differ', diffs, n;")
w("  END IF;")
w("  RAISE NOTICE 'FIXTURE BUILT — % ACL strings, all byte-exact against the production reading', n;")
w("END")
w("$verify$;")
w("")
w("-- The headline number R-50 reports for production. If the fixture does not")
w("-- reproduce it, nothing measured on the fixture is about production.")
w("DO $count$")
w("DECLARE c int;")
w("BEGIN")
w("  SELECT count(*) INTO c FROM pg_proc p")
w("   WHERE p.pronamespace = 'public'::regnamespace AND p.prokind='f'")
w("     AND p.provolatile='v' AND p.prosecdef AND p.prorettype <> 'trigger'::regtype")
w("     AND has_function_privilege('anon', p.oid, 'EXECUTE');")
w("  IF c <> 33 THEN RAISE EXCEPTION 'expected 33 anon-executable definer volatile functions, got %', c; END IF;")
w("  RAISE NOTICE '33 anon-executable SECURITY DEFINER VOLATILE functions — matches production';")
w("END")
w("$count$;")

print("\n".join(out))
