-- Unit B fixture stubs. Signatures exact; bodies irrelevant to an ACL test.
CREATE OR REPLACE FUNCTION public._ensure_stats_row(_a0 uuid) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.change_custom_url(_a0 text) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.claim_username(_a0 text) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.clear_custom_url() RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.custom_url_available(_a0 text, _a1 uuid) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.custom_url_ever_held(_a0 uuid) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.custom_url_fold_accents(_a0 text) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.custom_url_slug(_a0 text) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.custom_url_transliterate(_a0 text) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.delete_email(_a0 text, _a1 bigint) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.emit_notification(_a0 text, _a1 uuid, _a2 integer, _a3 uuid, _a4 text, _a5 text, _a6 text, _a7 uuid, _a8 text, _a9 jsonb, _a10 text) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.forbid_custom_url_change() RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.get_broadcast_feed(_a0 uuid[], _a1 integer) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.get_broadcast_feed(_a0 uuid[], _a1 integer, _a2 integer) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.get_broadcast_feed(_a0 uuid[], _a1 integer, _a2 integer, _a3 text[]) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.log_push_outcome(_a0 uuid, _a1 uuid, _a2 text, _a3 text, _a4 text) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.media_begin_upload(_a0 bytea, _a1 integer, _a2 integer, _a3 bigint, _a4 text) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.media_mark_ready(_a0 uuid, _a1 jsonb) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.media_mark_verified(_a0 uuid) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.media_migrate_post(_a0 uuid, _a1 uuid, _a2 jsonb) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.media_quarantine(_a0 uuid, _a1 text) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.move_to_dlq(_a0 text, _a1 text, _a2 bigint, _a3 jsonb) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.post_attach_media(_a0 uuid, _a1 uuid[]) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.post_publish_with_media(_a0 uuid[], _a1 text, _a2 text, _a3 text[], _a4 boolean, _a5 text, _a6 text[]) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.prevent_direct_custom_url_update() RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.process_referral_reward(_a0 uuid, _a1 text) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.process_referral_reward(_a0 uuid, _a1 text, _a2 numeric) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.publish_post_draft(_a0 uuid) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.recount_hashtags(_a0 uuid[]) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.search_certificates(_a0 text, _a1 text, _a2 date) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.suggest_hashtags(_a0 text, _a1 integer) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.tg_custom_url_reject_reserved() RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.tg_profiles_assign_custom_url() RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.tg_profiles_record_custom_url_history() RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.verify_certificate_by_token(_a0 text) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.wallet_ledger_v2_diff_snapshot(_a0 interval) RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE OR REPLACE FUNCTION public.ub_canary(_x text) RETURNS text LANGUAGE sql AS $$ SELECT _x $$;
