// GENERATED by scripts/web-media-authz-build.mjs from cloudflare/media-authz/*.ts and
// src/lib/video/shared/{playToken,rules}.ts. Do not edit; paste this whole file into the
// Cloudflare dashboard (cloudflare/media-authz/README.md). CI fails if it is stale.
// src/lib/video/shared/rules.ts
var VIDEO_FILE_RE = /^(master|(240|480|720)p|audio)(_\d{1,4})?\.(m3u8|m4s|mp4)$|^poster\.jpg$/;
function isAllowedFileName(name) {
  return typeof name === "string" && VIDEO_FILE_RE.test(name);
}
function contentTypeFor(name) {
  if (!isAllowedFileName(name)) return null;
  if (name.endsWith(".m3u8")) return "application/vnd.apple.mpegurl";
  if (name.endsWith(".m4s")) return "video/iso.segment";
  if (name.endsWith(".mp4")) return "video/mp4";
  if (name.endsWith(".jpg")) return "image/jpeg";
  return null;
}

// src/lib/video/shared/playToken.ts
var PLAY_TOKEN_TTL_S = 900;
var PLAY_TOKEN_SKEW_S = 60;
var PLAY_TOKEN_VERSION = "v1";
var UUID = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}";
var PREFIX_RE = new RegExp(`^video/${UUID}/${UUID}/v[1-9]\\d{0,5}/$`);
var HOST_RE = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/;
var SUB_RE = new RegExp(`^(${UUID}|anon)$`);
function fromB64url(s) {
  if (!/^[A-Za-z0-9_-]*$/.test(s)) return null;
  try {
    const bin = atob(s.replace(/-/g, "+").replace(/_/g, "/") + "===".slice((s.length + 3) % 4));
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  } catch {
    return null;
  }
}
async function importTokenKey(keyB64) {
  let raw;
  try {
    const bin = atob(keyB64.trim());
    raw = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) raw[i] = bin.charCodeAt(i);
  } catch {
    throw new Error("VID-TOK-002: MEDIA_TOKEN_KEY is not base64");
  }
  if (raw.length !== 32) throw new Error("VID-TOK-002: MEDIA_TOKEN_KEY must be 32 bytes");
  return crypto.subtle.importKey("raw", raw, { name: "HMAC", hash: "SHA-256" }, false, ["sign", "verify"]);
}
function claimsProblem(c) {
  if (!PREFIX_RE.test(c.prefix)) return "prefix";
  if (!Number.isInteger(c.exp) || c.exp <= 0) return "exp";
  if (!SUB_RE.test(c.sub)) return "sub";
  if (!HOST_RE.test(c.aud)) return "aud";
  return null;
}
function parsePayload(text) {
  const lines = text.split("\n");
  if (lines.length !== 5 || lines[0] !== PLAY_TOKEN_VERSION) return null;
  const take = (line, name) => line.startsWith(`${name}=`) ? line.slice(name.length + 1) : null;
  const prefix = take(lines[1], "prefix");
  const expS = take(lines[2], "exp");
  const sub = take(lines[3], "sub");
  const aud = take(lines[4], "aud");
  if (prefix === null || expS === null || sub === null || aud === null || !/^\d{1,12}$/.test(expS)) return null;
  const c = { prefix, exp: Number(expS), sub, aud };
  return claimsProblem(c) ? null : c;
}
async function verifyPlayToken(token, objectKey, host, nowS, keyB64) {
  if (!token) return { ok: false, reason: "no-token" };
  const dot = token.indexOf(".");
  if (dot <= 0 || dot !== token.lastIndexOf(".")) return { ok: false, reason: "shape" };
  const payload = fromB64url(token.slice(0, dot));
  const sig = fromB64url(token.slice(dot + 1));
  if (!payload || !sig || sig.length !== 32) return { ok: false, reason: "shape" };
  const key = await importTokenKey(keyB64);
  const good = await crypto.subtle.verify("HMAC", key, sig, payload);
  if (!good) return { ok: false, reason: "signature" };
  const claims = parsePayload(new TextDecoder().decode(payload));
  if (!claims) return { ok: false, reason: "payload" };
  if (claims.exp <= nowS) return { ok: false, reason: "expired" };
  if (claims.exp > nowS + PLAY_TOKEN_TTL_S + PLAY_TOKEN_SKEW_S) return { ok: false, reason: "lifetime" };
  if (claims.aud !== host.toLowerCase()) return { ok: false, reason: "aud" };
  if (!objectKey.startsWith(claims.prefix)) return { ok: false, reason: "prefix" };
  const rest = objectKey.slice(claims.prefix.length);
  if (rest.includes("/") || !isAllowedFileName(rest)) return { ok: false, reason: "file" };
  return { ok: true, claims };
}

// cloudflare/media-authz/handler.ts
var CACHE_HOST = "https://media-authz.cache.invalid";
var IMMUTABLE = "private, max-age=31536000, immutable";
var PLAYLIST = "private, max-age=60";
function corsHeaders(req, env) {
  const origin = req.headers.get("origin");
  if (!origin) return {};
  const allowed = (env.ALLOWED_ORIGINS ?? "").split(",").map((s) => s.trim()).filter(Boolean);
  return allowed.includes(origin) ? { "access-control-allow-origin": origin, vary: "Origin" } : {};
}
function refuse(status, req, env, extra = {}) {
  return new Response(null, {
    status,
    headers: { "cache-control": "no-store", "x-content-type-options": "nosniff", ...corsHeaders(req, env), ...extra }
  });
}
function rewritePlaylist(text, token) {
  const t = encodeURIComponent(token);
  const sibling = (u) => isAllowedFileName(u);
  let bad = false;
  const out = text.split("\n").map((raw) => {
    const line = raw.replace(/\r$/, "");
    const trimmed = line.trim();
    if (!trimmed) return line;
    if (trimmed.startsWith("#")) {
      return line.replace(/URI="([^"]*)"/g, (_m, u) => {
        if (!sibling(u)) {
          bad = true;
          return _m;
        }
        return `URI="${u}?t=${t}"`;
      });
    }
    if (!sibling(trimmed)) {
      bad = true;
      return line;
    }
    return `${trimmed}?t=${t}`;
  });
  return bad ? null : out.join("\n");
}
async function handleMediaRequest(req, env, deps) {
  const url = new URL(req.url);
  let key;
  try {
    key = decodeURIComponent(url.pathname.slice(1));
  } catch {
    return refuse(400, req, env);
  }
  if (key.startsWith("/") || key.includes("//") || key.includes("\\") || key.split("/").includes("..")) {
    return refuse(400, req, env);
  }
  if (/^(video|upload)\//.test(key) && (/%2f|%5c/i.test(url.pathname) || key.split("/").includes("."))) {
    return refuse(400, req, env);
  }
  if (key.startsWith("upload/")) return refuse(404, req, env);
  if (!key.startsWith("video/")) return deps.passthrough(req);
  if (req.method === "OPTIONS") {
    const cors = corsHeaders(req, env);
    if (!cors["access-control-allow-origin"]) return refuse(403, req, env);
    return new Response(null, {
      status: 204,
      headers: { ...cors, "access-control-allow-methods": "GET, HEAD", "access-control-max-age": "86400", "cache-control": "no-store" }
    });
  }
  if (req.method !== "GET" && req.method !== "HEAD") return refuse(405, req, env, { allow: "GET, HEAD, OPTIONS" });
  const keyB64 = env.MEDIA_TOKEN_KEY;
  if (!keyB64 || !env.VIDEO_REVOKED) return refuse(503, req, env);
  try {
    await importTokenKey(keyB64);
  } catch {
    return refuse(503, req, env);
  }
  const token = url.searchParams.get("t");
  const verdict = await verifyPlayToken(token, key, url.hostname, Math.floor(deps.nowMs() / 1e3), keyB64);
  if (!verdict.ok) return refuse(403, req, env);
  const videoId = key.split("/")[2];
  if (await env.VIDEO_REVOKED.get(videoId) !== null) return refuse(403, req, env);
  const file = key.slice(verdict.claims.prefix.length);
  const type = contentTypeFor(file);
  if (!type) return refuse(403, req, env);
  const isPlaylist = file.endsWith(".m3u8");
  const cacheReq = new Request(`${CACHE_HOST}/${url.hostname}/${key}`);
  let bodyBytes = null;
  let etag = "";
  const hit = deps.cache ? await deps.cache.match(cacheReq) : void 0;
  if (hit) {
    bodyBytes = new Uint8Array(await hit.arrayBuffer());
    etag = hit.headers.get("etag") ?? "";
  } else {
    const obj = await env.MEDIA.get(key);
    if (!obj) return refuse(404, req, env);
    bodyBytes = new Uint8Array(await obj.arrayBuffer());
    etag = obj.httpEtag;
    if (deps.cache && req.method === "GET") {
      const stored = new Response(bodyBytes.slice(), {
        headers: { etag, "content-type": type, "cache-control": isPlaylist ? "public, max-age=60" : "public, max-age=31536000, immutable" }
      });
      deps.waitUntil(deps.cache.put(cacheReq, stored));
    }
  }
  let out = bodyBytes;
  if (isPlaylist) {
    const rewritten = rewritePlaylist(new TextDecoder().decode(bodyBytes), token ?? "");
    if (rewritten === null) return refuse(502, req, env);
    out = rewritten;
  }
  const headers = {
    "content-type": type,
    "x-content-type-options": "nosniff",
    "content-security-policy": "sandbox; default-src 'none'",
    "cache-control": isPlaylist ? PLAYLIST : IMMUTABLE,
    ...corsHeaders(req, env)
  };
  if (etag && !isPlaylist) headers.etag = etag;
  return new Response(req.method === "HEAD" ? null : out, { status: 200, headers });
}

// cloudflare/media-authz/worker.ts
var worker_default = {
  async fetch(request, env, ctx) {
    const cache = globalThis.caches?.default;
    return handleMediaRequest(request, env, {
      nowMs: () => Date.now(),
      cache,
      passthrough: (req) => fetch(req),
      waitUntil: (p) => ctx.waitUntil(p)
    });
  }
};
export {
  worker_default as default
};
