-- ============================================================================
-- EVERY NEW MEMBER GETS A PICTURE AT REGISTRATION — AUTOMATICALLY.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- OWNER ORDER, 2026-08-05:
--
--   "I told DP is must, either by user, or by icon generated by 50mm, during
--    registration time automatically must be and easy registration will go on.
--    after that allow text and photo and comment as normal."
--
-- WHAT WAS WRONG. The cartoons were handed out by a ONE-TIME BACKFILL
-- (20260805070000_fallback_avatars.sql) that updated the 33 members who existed
-- that day. `handle_new_user()` — the trigger that creates a profile row the
-- moment somebody registers — still wrote:
--
--     INSERT INTO public.profiles (id, full_name, avatar_url) VALUES (…, NULL)
--
-- So the backfill fixed yesterday and did nothing for tomorrow: every member
-- registering from now on would arrive with NO picture at all and be sent
-- straight into the "upload a photo" wall. Measured before this migration:
-- 0 members with no avatar today, 33 with a cartoon — and a brand-new signup
-- would have become the 1st with none.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- WHAT THIS DOES
--
-- 1. `handle_new_user()` now assigns a cartoon in the same INSERT that creates
--    the profile. There is no window in which a member exists without a
--    picture, and no client code has to remember to do it — web, app, Google
--    sign-in and any future path all go through this one trigger.
--
--    GENDER IS NOT KNOWN YET at this moment (the profile row is created by the
--    auth signup, before the member has answered He / She). The owner's formula,
--    given 2026-08-05, settles it: *"by default male image will fill up but when
--    user select she instaly female any icon will take place"*. So the face
--    comes from the male five, and moves the instant they answer She — both in
--    the form (derived client-side, see OnboardingModal) and in the row (the
--    trigger below).
--
-- 2. A new trigger re-points that cartoon the moment the member answers
--    He / She, so the automatic choice becomes a fitting one. It fires ONLY
--    when `gender` actually changes, ONLY when the member has no uploaded
--    photo, and ONLY when the current picture is one of ours — a real
--    uploaded portrait is never touched, and neither is a member who has
--    deliberately picked a different cartoon after answering.
--
-- WHY THE INDEX IS PRESERVED across the re-point: a member auto-assigned f3
-- who then answers "He" becomes m3, not a random male face. Same person, same
-- slot, so the picture does not jump around more than it has to.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- THIS DOES NOT MAKE A CARTOON COUNT AS A PROFILE PHOTO.
--
-- The value is still a SITE-RELATIVE path, and `public.has_profile_photo()` /
-- `isOwnProfilePhoto()` are allowlists of our own upload storage. So the "add
-- your photo" prompt keeps asking, and when the owner reinstates the photo rule
-- at ~1000 members it still means a photo the member actually uploaded.
--
-- WHAT IS DELIBERATELY LEFT ALONE in handle_new_user(): the first-admin
-- branding rule and the OAuth display-name logic are copied through unchanged.
-- The ONLY behavioural change is the avatar_url value.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  _oauth_name text;
  _is_first_admin boolean;
BEGIN
  _oauth_name := COALESCE(
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'name',
    NULL
  );
  SELECT NOT EXISTS (SELECT 1 FROM public.user_roles WHERE role = 'admin') INTO _is_first_admin;

  -- avatar_url is NOT the OAuth picture — that is a third-party hotlink which
  -- never counted under the own-storage policy and now 503s from Google. It is
  -- one of our own cartoons. Gender is not known at this moment, so per the
  -- owner's formula the MALE five are the default and the trigger below moves
  -- it the instant the member answers She.
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    NEW.id,
    CASE WHEN _is_first_admin THEN '50mm Retina World' ELSE _oauth_name END,
    '/avatars/fallback/m'
      || ((abs(hashtext(NEW.id::text)) % 5) + 1)::text
      || '.svg'
  );

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'user');
  RETURN NEW;
END;
$function$;


-- ── Re-point the cartoon once the member says He / She ──────────────────────
CREATE OR REPLACE FUNCTION public.sync_fallback_avatar_to_gender()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  -- Only when the answer actually changed, and only to a real answer.
  IF NEW.gender IS NOT DISTINCT FROM OLD.gender OR NEW.gender IS NULL THEN
    RETURN NEW;
  END IF;

  -- Never touch an uploaded photo, and never touch anything that is not one of
  -- our own cartoons (a member who set something else chose it deliberately).
  IF NEW.avatar_url IS NULL OR NEW.avatar_url NOT LIKE '/avatars/fallback/%' THEN
    RETURN NEW;
  END IF;

  -- Keep the SLOT, swap the SET: f3 -> m3, not f3 -> m1.
  NEW.avatar_url :=
    '/avatars/fallback/'
    || CASE WHEN NEW.gender = 'female' THEN 'f' ELSE 'm' END
    || regexp_replace(NEW.avatar_url, '^/avatars/fallback/[mf]([1-5])\.svg$', '\1')
    || '.svg';

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_sync_fallback_avatar_to_gender ON public.profiles;
CREATE TRIGGER trg_sync_fallback_avatar_to_gender
  BEFORE UPDATE OF gender ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_fallback_avatar_to_gender();

COMMENT ON FUNCTION public.sync_fallback_avatar_to_gender() IS
  'Re-points a members stand-in cartoon to the set matching their He/She answer, keeping the same slot number. Never touches an uploaded photo.';


-- ── 3. A member may NEVER end up with no picture at all ─────────────────────
--
-- ADDED THE SAME DAY, after a bug of mine proved the rule needed enforcing
-- rather than trusting. Removing the photo requirement from onboarding made
-- `handleFinish` write `avatar_url: ""` for anybody who skipped it, which
-- OVERWROTE the cartoon assigned above. It hit one member — the owner's own
-- test account — before it was caught.
--
-- The client bug is fixed, but "DP is must, either by user, or by icon
-- generated by 50mm" is a rule about the DATA, so the database is where it
-- belongs. Any write that would blank avatar_url is turned into "assign the
-- fitting stand-in" instead. No client, present or future, can undo it.
CREATE OR REPLACE FUNCTION public.ensure_member_always_has_picture()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.avatar_url IS NULL OR btrim(NEW.avatar_url) = '' THEN
    NEW.avatar_url := '/avatars/fallback/'
      || CASE WHEN NEW.gender = 'female' THEN 'f' ELSE 'm' END
      || ((abs(hashtext(NEW.id::text)) % 5) + 1)::text || '.svg';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_ensure_member_always_has_picture ON public.profiles;
CREATE TRIGGER trg_ensure_member_always_has_picture
  BEFORE INSERT OR UPDATE OF avatar_url ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.ensure_member_always_has_picture();

COMMENT ON FUNCTION public.ensure_member_always_has_picture() IS
  'Guarantees every member has a picture. A write that would blank avatar_url becomes an assignment of the stand-in matching their He/She answer. Verified on production: members with no picture = 0.';
